Fixed Exercices

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -5,6 +5,7 @@ on:
   pull_request:
     branches: [main]
     types: [opened, synchronize]
+
 jobs:
   Lint:
     runs-on: ubuntu-22.04
@@ -13,12 +14,22 @@ jobs:
         uses: actions/checkout@v4
         with:
           fetch-depth: 0
+
       - name: Install node
         uses: actions/setup-node@v3
         with:
           node-version: 18
           cache: npm
+
       - name: Install dependencies
         run: npm install
+
       - name: Lint code
         run: npm run lint
+
+      - name: Check component file names
+        run: |
+          if [ $(find . -name "*.jsx" -not -path "./node_modules/*" -not -path "./build/*" -exec basename {} \; | grep -Pv '^[A-Z][a-z0-9]+\.jsx$' | wc -l) -gt 0 ]; then
+            echo "Error: Component file names must be in PascalCase."
+            exit 1
+          fi
